[versions]

#Common build.gradle
gradle = "8.11.1"
kotlin = "2.2.0"

#Project build.gradle
hilt-android-gradle-plugin = "2.57"

#Common
core-ktx = "1.16.0"
material = "1.12.0"

#Unit tests
junit = "4.13.2"
io-mockk = "1.14.5"
org-jetbrains-kotlinx-coroutines-test = "1.10.2"
app-cash-turbine = "1.2.1"

#Instrumented Tests
ax-test-ext-junit-ktx = "1.2.1"
ax-test-expresso-core = "3.6.1"

#Compose
compose-bom = "2025.07.00"
ax-constraintlayout-compose = "1.1.1"
ax-activity-compose = "1.10.1"
ax-navigation-compose = "2.9.2"
lifecycle-viewmodel-compose = "2.9.2"
kotlinx-serialization-json = "1.9.0"

#Paging
ax-paging-runtime-ktx = "3.3.6"
ax-paging-compose = "3.3.6"

#Compose Navigation 3
ax-navigation3-runtime = "1.0.0-alpha05"
ax-navigation3-ui = "1.0.0-alpha05"
ax-navigation3-viewmodel = "1.0.0-alpha03"

#Dagger & Hilt
hilt-android = "2.57"
hilt-android-compiler = "2.57"
hilt-common = "1.2.0"
hilt-compiler = "1.2.0"
ax-hilt-navigation-compose = "1.2.0"

#OkHttp
okhttp-bom = "5.1.0"

#Moshi
moshi-kotlin = "1.15.2"
moshi-kotlin-codegen = "1.15.2"

#Retrofit 3
retrofit2 = "3.0.0"
retrofit2-kotlinx-serialization-converter = "1.0.0"

#Lifecycle
ax-lifecycle-runtime-ktx = "2.9.2"
ax-lifecycle-common = "2.9.2"
ax-lifecycle-common-java8 = "2.9.2"
ax-lifecycle-viewmodel-savedstate = "2.9.2"
ax-lifecycle-viewmodel-ktx = "2.9.2"

#Lifecycle Extensions
ax-lifecycle-extensions = "2.2.0"

#Splashscreen
ax-splashscreen = "1.0.1"

#Other
io-coil-kt-coil-compose = "2.7.0"

#Plugins

#Common
com-google-devtools-ksp = "2.2.0-2.0.2"

[libraries]

#build-logic
android-gradle-plugin-library = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
kotlin-gradle-plugin-library = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin-library = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "com-google-devtools-ksp" }

#Common
ax-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
com-google-android-material = { module = "com.google.android.material:material", version.ref = "material" }

#Unit tests
junit = { module = "junit:junit", version.ref = "junit" }
io-mockk = { module = "io.mockk:mockk", version.ref = "io-mockk" }
org-jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx-coroutines-test" }
app-cash-turbine = { module = "app.cash.turbine:turbine", version.ref = "app-cash-turbine" }

#Instrumented Tests
ax-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "ax-test-ext-junit-ktx" }
ax-test-expresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "ax-test-expresso-core" }

#Compose
ax-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ax-compose-ui = { group = "androidx.compose.ui", name = "ui" }
ax-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ax-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ax-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ax-compose-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding" }
ax-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
ax-compose-runtime-rxjava3 = { group = "androidx.compose.runtime", name = "runtime-rxjava3" }
ax-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
ax-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
ax-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
ax-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "ax-constraintlayout-compose" }
ax-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "ax-activity-compose" }
ax-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
ax-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "ax-navigation-compose" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

#Paging
ax-paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "ax-paging-runtime-ktx" }
ax-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "ax-paging-compose" }

#Compose Navigation 3
##Core Navigation 3 libraries
ax-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "ax-navigation3-runtime" }
ax-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "ax-navigation3-ui" }

#Dagger & Hilt
ax-hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "hilt-common" }
ax-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-compiler" }
ax-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "ax-hilt-navigation-compose" }
com-google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
com-google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android-compiler" }

#ViewModel integration and adaptive layouts
ax-navigation3-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "ax-navigation3-viewmodel" }

#OkHttp
com-squareup-okhttp3-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp-bom" }
com-squareup-okhttp3 = { module = "com.squareup.okhttp3:okhttp" }
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

#Moshi
com-squareup-moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-kotlin" }
com-squareup-moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi-kotlin-codegen" }

#Retrofit 3
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-kotlinx-serialization-converter" }

#Lifecycle
ax-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "ax-lifecycle-runtime-ktx" }
ax-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "ax-lifecycle-common" }
ax-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "ax-lifecycle-common-java8" }
ax-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "ax-lifecycle-viewmodel-savedstate" }
ax-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "ax-lifecycle-viewmodel-ktx" }

#Lifecycle Extensions
ax-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "ax-lifecycle-extensions" }

#Splashscreen
ax-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "ax-splashscreen" }

io-coil-kt-coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "io-coil-kt-coil-compose" }

[plugins]

#Common
com-android-application = { id = "com.android.application", version.ref = "gradle" }
com-android-library = { id = "com.android.library", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools-ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

#Project build.gradle
hilt-android-gradle-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android-gradle-plugin" }
